apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: cxl.intel.com
spec:
  selectors:
  - cel:
      expression: device.driver == "cxl.intel.com"
  # Uncomment to request the devices as an extended resource. See
  # https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/5004-dra-extended-resource
  # extendedResourceName: intel.com/cxl
